"use client";

import { useState, useRef, useEffect, type FormEvent } from "react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Bot, Loader2, SendHorizonal, User, Code2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { Logo } from "./logo";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  type?: "text" | "code";
}

export function ChatView() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isDevMode, setIsDevMode] = useState(false);
  const scrollAreaRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const viewport = scrollAreaRef.current?.querySelector("div[data-radix-scroll-area-viewport]");
    if (viewport) {
      viewport.scrollTop = viewport.scrollHeight;
    }
  }, [messages]);

  const handleSendMessage = async (e: FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
      type: "text",
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);
    
    await new Promise((resolve) => setTimeout(resolve, 1500));

    let aiResponse: Message;

    if (isDevMode) {
      aiResponse = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: `// Simulated code response for: "${userMessage.content}"\nfunction helloWorld() {\n  console.log("Hello, Developer World!");\n}`,
        type: "code",
      };
    } else {
      aiResponse = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: `This is a simulated response based on your prompt: "${userMessage.content}". In a real application, this response would be generated by the Gemini AI.`,
        type: "text",
      };
    }

    setMessages((prev) => [...prev, aiResponse]);
    setIsLoading(false);
  };

  return (
    <div className="flex h-[calc(100vh-49px)] flex-col">
        <div className="flex items-center justify-between border-b p-2 px-4">
            <h2 className="text-sm font-medium">Conversation</h2>
            <div className="flex items-center space-x-2">
                <Code2 className="h-4 w-4 text-muted-foreground" />
                <Label htmlFor="dev-mode-switch">Developer Mode</Label>
                <Switch id="dev-mode-switch" checked={isDevMode} onCheckedChange={setIsDevMode} />
            </div>
        </div>
      <ScrollArea className="flex-1" ref={scrollAreaRef}>
        <div className="p-4 md:p-6">
            {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center gap-4 text-center h-full pt-20 animate-in fade-in duration-500">
                    <Logo className="h-16 w-16 text-primary/50" />
                    <h2 className="text-2xl font-bold">Adigon AI Assistant</h2>
                    <p className="text-muted-foreground">Start a conversation by typing a message below.</p>
                </div>
            )}
            <div className="space-y-4">
            {messages.map((message) => (
                <div
                    key={message.id}
                    className={cn(
                        "flex items-start gap-3 animate-in fade-in-0 zoom-in-95 duration-300",
                        message.role === "user" && "justify-end"
                    )}
                >
                    {message.role === "assistant" && (
                        <Avatar className="h-8 w-8 shrink-0 border"><AvatarFallback><Bot size={18}/></AvatarFallback></Avatar>
                    )}
                    <div
                        className={cn(
                            "max-w-xl rounded-xl px-4 py-2.5",
                            message.role === "user"
                            ? "bg-primary text-primary-foreground"
                            : "bg-card",
                        )}
                    >
                        {message.type === 'code' ? (
                            <pre className="text-sm overflow-x-auto bg-card rounded-md p-0"><code className="font-code">{message.content}</code></pre>
                        ) : (
                            <p className="whitespace-pre-wrap text-sm">{message.content}</p>
                        )}
                    </div>
                    {message.role === "user" && (
                        <Avatar className="h-8 w-8 shrink-0 border"><AvatarFallback><User size={18}/></AvatarFallback></Avatar>
                    )}
                </div>
            ))}
            {isLoading && (
                <div className="flex items-start gap-3 animate-in fade-in">
                    <Avatar className="h-8 w-8 shrink-0 border"><AvatarFallback><Bot size={18}/></AvatarFallback></Avatar>
                    <div className="bg-card rounded-xl px-4 py-3 flex items-center justify-center">
                        <Loader2 className="h-5 w-5 animate-spin text-primary" />
                    </div>
                </div>
            )}
            </div>
        </div>
      </ScrollArea>
      <div className="border-t bg-background/80 backdrop-blur-sm">
        <div className="p-4 max-w-3xl mx-auto">
            <form onSubmit={handleSendMessage} className="relative">
            <Textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                        e.preventDefault();
                        handleSendMessage(e);
                    }
                }}
                placeholder={isDevMode ? "Describe the code you want to generate..." : "Ask me anything..."}
                className="w-full resize-none pr-16 min-h-[40px]"
                rows={1}
                disabled={isLoading}
            />
            <Button
                type="submit"
                size="icon"
                variant="ghost"
                className="absolute bottom-1.5 right-1.5 h-8 w-8 rounded-full"
                disabled={isLoading || !input.trim()}
            >
                <SendHorizonal size={20} />
                <span className="sr-only">Send</span>
            </Button>
            </form>
        </div>
      </div>
    </div>
  );
}
